version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./db/volume:/var/lib/mysql
    env_file:
      - ./db/env.dev
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -P 3306 --protocol=tcp -u askuser --password=askpw
        start_period: 5s
        interval: 5s
        timeout: 5s
        retries: 10
  web:
    container_name: web
    build: ./web
    ports:
      - 8081:8081
    env_file:
      - ./web/.env.dev
    depends_on:
      db:
        condition: service_healthy
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    volumes:
      - ./web/static:/static
      - ./web/uploads:/uploads
    ports:
      - 80:80
    depends_on:
      - web